data:
  data_root_dir: /workspace
  data_mix: bridge_orig  # 或 bridge_dataset，根据数据集结构调整
  prompt_key: steps/language_instruction  # 匹配数据集字段
  answer_key: steps/action               # 已正确加载为 actions
  image_key: steps/observation/image_0   # 使用 image_0
  max_prompt_length: 128
  max_response_length: 7
  # rollout_batch_size: 4
  rollout_batch_size: 2
  shuffle: true
  seed: 1
  max_pixels: 150528
  min_pixels: 150528

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    # global_batch_size: 4
    global_batch_size: 2
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 1
    max_grad_norm: 1.0
    entropy_coeff: 1.0e-3
    use_kl_loss: true
    kl_loss_coef: 1.0e-3
    kl_loss_type: low_var_kl
    padding_free: false
    ulysses_sequence_parallel_size: 1
    model:
      model_path: /workspace/models/openvla-7b
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: false
    optim:
      lr: 1.0e-5
      weight_decay: 0.1
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: false
      offload_optimizer: false

  rollout:
    temperature: 0.6
    n: 1
    gpu_memory_utilization: 0.5
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    compute_score: action

trainer:
  total_episodes: 15
  # logger: ["console", "wandb"]
  logger: ["console"]
  project_name: easy_r1
  experiment_name: openvla_7b_robot
  n_gpus_per_node: 1
  nnodes: 1
  val_freq: 0
  val_before_train: false
  val_only: false
  val_generations_to_log: 1
  save_freq: 5
  remove_previous_ckpt: false
  remove_ckpt_after_load: false